apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: default
  namespace: default
spec:
  host: apps-test.ucsd.edu
  upstreams:
  - name: v1
    service: test-app-v1
    port: 3000
  - name: v2
    service: test-app-v2
    port: 3000
  subroutes:
  - path: /
    splits:
    - weight: 50
      action:
        pass: v1
    - weight: 50
      action:
        pass: v2
